# vim: noai:ts=2:sw=2:expandtab
---
- name: Language packs
  apt: name="{{item}}"
  with_items:
    - language-pack-de-base
    - language-pack-de
    - language-pack-gnome-de-base
    - language-pack-gnome-de
    - wswiss
    - wngerman
    - wogerman
    - wbritish
    - thunderbird-locale-en-us
    - thunderbird-locale-en
    - thunderbird-locale-en-gb
    - thunderbird-locale-de
    - firefox-locale-de
    - firefox-locale-en
    - libreoffice-help-en-us
    - libreoffice-help-en-gb
    - libreoffice-l10n-en-gb
    - libreoffice-l10n-en-za
    - libreoffice-l10n-de
    - libreoffice-help-de
    - openoffice.org-hyphenation
    - hunspell-en-ca
    - hunspell-de-de
    - hunspell-de-ch
    - hunspell-de-at
    - hyphen-de
    - hyphen-en-us
    - myspell-en-au
    - myspell-en-za
    - myspell-en-gb
    - mythes-de-ch
    - mythes-en-au
    - mythes-en-us
    - mythes-de
  tags:
    - configuration
- name: Locale settings
  command: update-locale LANG=de_DE.UTF-8 LC_MESSAGES=POSIX
  tags:
    - configuration

- command: locale-gen
  tags:
    - configuration

- name: Keyboard configuration
  debconf: name='keyboard-configuration' question={{item.question}} value={{item.value}} vtype={{item.vtype}}
  become: true
  become_user: "{{user}}"
  with_items:
    - { question: 'keyboard-configuration/layout', value: 'German', vtype: 'select' }
    - { question: 'keyboard-configuration/layoutcode', value: 'de', vtype: 'select' }
    - { question: 'keyboard-configuration/variantcode', value: 'nodeadkeys', vtype: 'select' }
    - { question: 'keyboard-configuration/modelcode', value: 'pc105', vtype: 'select' }
    - { question: 'keyboard-configuration/optionscode', value: 'compose:rctrl', vtype: 'select' }
  tags:
    - configuration

- name: Git configuration
  template: src=gitconfig.j2 dest="{{home}}/.gitconfig" owner="{{user}}" group="{{user}}" mode=0664
  tags:
    - configuration

- name: Disable automatic login
  template: src=custom.conf.j2 dest="/etc/gdm/custom.conf" backup=yes mode=0644
  tags:
    - configuration
