- name: Install ruby 2.1.3
  shell: "{{home}}/.rvm/bin/rvm install 2.1.3"
  become: true
  become_user: "{{user}}"
  tags: [asciidoctor]

- name: Install Asciidoctor
  shell: "{{home}}/.rvm/bin/rvm 2.1.3 do gem install guard guard-shell guard-livereload yajl-ruby asciidoctor" 
  args:
    creates: "{{home}}/.rvm/gems/ruby-2.1.3/bin/asciidoctor"
  become: true
  become_user: "{{user}}"
  tags: [asciidoctor]



