  ## vim: noai:ts=2:sw=2:expandtab
---
- name: Ambiance Theme Repository, theme-manager, cairo-dock
  apt_repository: repo={{ item }}
  environment: proxy_env
  with_items:
    - "ppa:ravefinity-project/ppa"
    - "ppa:rebuntu16/other-stuff"
    - "ppa:cairo-dock-team/ppa"
    - "ppa:xubuntu-dev/xfce-4.12"
    - "ppa:xubuntu-dev/extras"
  tags: xubuntu
# upgrade to xfce 4.12
- name: upgrade to xfce 4.12
  apt: upgrade=dist
  tags: xubuntu
- name: additional packages
  apt: name="{{item}}"
  with_items:
    - xubuntu-desktop
    - cairo-dock
    - libreoffice-gtk
    - xfce-theme-manager
    - ambiance-flat-colors 
    - radiance-flat-colors
    - xscreensaver
    - xfdashboard
# for xfce 4.12 and qt (only for 14.04)
    - qt4-qtconfig
  tags: xubuntu
- name: remove packages
  apt: name="{{item}}" state=absent 
  with_items:
    - abiword
    - light-locker
  tags: xubuntu
- name: Wallpaper
  get_url: url=http://gnome-look.org/CONTENT/content-files/100418-3dbuntu3.jpg dest=/usr/share/xfce4/backdrops/100418-3dbuntu3.jpg
  environment: proxy_env
  tags: configuration
- name: xfce4 | configuration | ensure directory
  file: path={{home}}/.config state=directory
  become: True
  become_user: "{{user}}"
  tags: xubuntu
- name: xfce4 | copy config
  unarchive: src=xfce4-config.tar.gz dest={{home}}
  become: True
  become_user: "{{user}}"
  tags: xubuntu
#- name: Disable automatic login
#  template: src=custom.conf.j2 dest="/etc/gdm/custom.conf" backup=yes mode=0644
#  tags: configuration
