## vim: noai:ts=2:sw=2:expandtab
---
- name: ambiance theme repository
  apt_repository: repo='ppa:ravefinity-project/ppa'
  environment: proxy_env
  tags: xubuntu
- name: xfwm-theme-manager Repository
  apt_repository: repo='ppa:rebuntu16/other-stuff'
  tags: xubuntu
- name: additional packages
  apt: name="{{item}}"
  with_items:
    - xubuntu-desktop
    - cairo-dock
    - libreoffice-gtk
    - xfce-theme-manager
    - ambiance-flat-colors 
    - radiance-flat-colors
  tags: xubuntu
- name: remove packages
  apt: name=abiword state=absent 
  tags: xubuntu
- name: Wallpaper
  get_url: url=http://gnome-look.org/CONTENT/content-files/100418-3dbuntu3.jpg dest=/usr/share/xfce4/backdrops/100418-3dbuntu3.jpg
  environment: proxy_env
  tags: configuration
#- name: Disable automatic login
#  template: src=custom.conf.j2 dest="/etc/gdm/custom.conf" backup=yes mode=0644
#  tags: configuration
