# vim: noai:ts=2:sw=2:expandtab
---
- apt: name={{item}} state=present 
  with_items:
    - vim
    - build-essential
    - cmake
    - python-dev

- name: Install Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest={{home}}/.vim/bundle/Vundle.vim
  become: true
  become_user: "{{user}}"

- name: Download vimrc
  get_url: url="https://gist.githubusercontent.com/rattermeyer/4f2b0d48069a2f5345fd/raw/0df71628a7134950543042ef68ff5234911f1601/vimrc" dest={{home}}/.vimrc
  become: true
  become_user: "{{user}}"

# not sure if this is enough
- name: Install Powerline Font
  file: path={{home}}/.fonts state=directory
  become: true
  become_user: "{{user}}"
- get_url: url="https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf" dest={{home}}/.fonts/PowerlineSymbols.otf
  tags: powerline
  become: true
  become_user: "{{user}}"

- command: fc-cache -vf {{home}}/.fonts
  tags: powerline
  become: true
  become_user: "{{user}}"

- file: path={{home}}/.config/fontconfig/conf.d state=directory 
  tags: powerline
  become: true
  become_user: "{{user}}"

- get_url: url="https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf" dest={{home}}/.config/fontconfig/conf.d/10-powerline-symbols.conf
  tags: powerline
  become: true
  become_user: "{{user}}"

## end: Powerline

- name: YouCompleteMe
  git: repo=https://github.com/Valloric/YouCompleteMe.git dest={{home}}/.vim/bundle/YouCompleteMe
  become: true
  become_user: "{{user}}"

- name: YouCompleteMe compile
  command: ./install.sh --clang-completer creates="{{home}}/.vim/bundle/YouCompleteMe/python/ycm/__init__.pyc" chdir="{{home}}/.vim/bundle/YouCompleteMe"
  become: true
  become_user: "{{user}}"

- command: vim +PluginInstall +qall 2&> /dev/null
  become: true
  become_user: "{{user}}"
